# This is a config for E2B sandbox template.
# You can use template ID (ftygri7jtojrgk5gu6kg) or template name (webly-nextjs-test2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("webly-nextjs-test2") # Sync sandbox
# sandbox = await AsyncSandbox.create("webly-nextjs-test2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('webly-nextjs-test2')

team_id = "b7f9c764-bd46-4503-ab24-08710ac1eaec"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "webly-nextjs-test2"
template_id = "ftygri7jtojrgk5gu6kg"
